/**
 * EndpointController
 *
 * @module      :: Controller
 * @description :: 
 */

var Chance = require('chance');
var chance = new Chance();

module.exports = {
    
  create: function(req, res){
    
    // Endpoint Attributes
    var endpointId = chance.guid();
    var endpointType = req.param('type');
    var endpointHttpStatus = req.param('httpStatus');
    var endpointData = req.param('data');
    var valueType = req.param('valueType');

    // Save record
    Endpoint.create({
      "uuid": endpointId,
      "type": endpointType,
      "httpStatus": endpointHttpStatus,
      "data": endpointData
    }).done(function(err, endpoint) {

      if(err){
        return res.json('Error creating endpoint', 400);
      }

      return res.json(endpointId);
    });

  },

  // Serve the data for the given endpoint
  // Invoked example: geekster.io/60B3780D-DE2F-55FD
  serve: function (req, res) {

    // Allow Cross Origin so that it can be called from anywhere
    res.header('Access-Control-Allow-Origin', req.headers.origin);
    res.header('Content-Type', 'application/json');

    // Get endpoint uuid from the request
    var endpointId = req.param('uuid');

    // Query the database to find the requested endpoint
    Endpoint.findOne({ uuid: endpointId}, function(err, endpoint) {

      // 404 in case the record is not found
      if(err){
        return res.json('endpoint not found', 404);
      }

      // Return the response generated by the Strategy service
      return res.send(ServeStrategy.serve(endpoint), endpoint.httpStatus);
    });

  },


  // For admin purposes. should not be public
  // Returns all the records in the database
  list: function(req, res){

    var Chance = require('chance');
    var chance = new Chance();
    var response = {};

    Endpoint.find().exec(function(err, endpoints) {
      return res.json(endpoints);
    });

  },


  /**
   * Overrides for the settings in `config/controllers.js`
   * (specific to EndpointController)
   */
  _config: {}

};